spring:
  application:
   name: code-genie
  datasource:
   url: jdbc:mysql://localhost:3306/code-genie
   username: root
   password: mysql80
server:
  port: 8080


# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.chen.codegenie.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn
